'use client'
//TODO QUITAR EL USE CLIENTE DE LAYOUT 
import AuthProvider from "@/components/providers/AuthProvider";
import "./globals.css";
import { Inter } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <AuthProvider>
        <body className={`h-screen ${inter.className}`}>
          <main className="h-full">{children}</main>
          <Toaster />
        </body>
      </AuthProvider>
    </html>
  );
}
